config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :devise, :path => "/" do
    #Registrations
    post 'sign_up' => 'registrations#create'
     get 'confirm_email' => 'registration#confirm_email'
    

    #Sessions
    get 'login' => 'sessions#new'
    post 'login'  => 'sessions#create'

    
  end
  resources :skus
  post '/new_csv' => 'skus#new_csv'
  root :to => "devise/registrations#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sku.rb
class Sku < ApplicationRecord
	require 'csv'
	belongs_to :user
	validates_presence_of :sku_denominations, :sku_combinations

  def self.to_csv(fields = ["sku_denominations","sku_combinations"], options={})
	   CSV.generate(options) do |csv|
	   csv << fields
	   all.each do |sku|
	     csv << sku.attributes.values_at(*fields)
	   end
	  end
	 end

end

app/models/user.rb
class User < ApplicationRecord
	has_many :skus
	before_create :confirmation_token
	validates_uniqueness_of :email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]


  def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
			user.email = auth.info.email
			user.provider = auth.provider
			user.uid = auth.uid
			user.password = Devise.friendly_token[0,20]
		end
	end

  private
  def confirmation_token
    if self.confirm_token.blank?
        self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/skus_controller.rb
class SkusController < ApplicationController

	def new
		@sku = Sku.new
	end

	def create
		@user = current_user
		@sku_denominations = params[:sku_denominations].to_i
		if params[:csv].present?
			@option1_sku = []
			@option2_sku = []
			@option3_sku = []
			sku_hash_arr = []
			file =  params[:csv]
			csv_arr = CSV.read(file.path)
			if csv_arr.include? ["option1_sku", "option2_sku", "option3_sku"]
				csv_arr.each_with_index do |csv, i|
					if i > 0
						@option1_sku << csv[0] if csv.first.present?
						@option2_sku << csv[1] if csv.second.present?
	          @option3_sku <<  csv[2] if csv.third.present?
	        end
				end

				@option1_sku.compact.each do |option1|
          @option2_sku.compact.each do |option2|
          	@option3_sku.compact.each do |option3|
          		@combination = option1 + "," + option2 + "," + option3
              sku_hash = {sku_combinations: @combination,sku_denominations: @sku_denominations,user_id: current_user.id}
          		sku_hash_arr << sku_hash
          		@sku_denominations += 1

          	end
          end
				end
				@skus = Sku.create(sku_hash_arr)	
        @ids = @skus.map(&:id)
			else
				flash[:error] = "File format is not correct"
			end
		end
	end

	def new_csv
		@skus = Sku.where(id: params[:ids])
		# @skus = Sku.all
		data = @skus
		respond_to do |format|
      format.html
      format.csv { send_data @skus.to_csv, :type => 'text/csv', filename: "skus-#{Date.today}.csv" }
    end
	end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect new_sku_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/skus_helper.rb
module SkusHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js', 'https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.js', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path  %> |
      <%= link_to "Login", new_user_session_path  %>
    <% end %>
    <div class= "flash-error top-flash-error">
      <%= render partial: "devise/shared/flash" %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/skus/_download_csv_file.html.erb
	<%= link_to "<button>CSV Download</button>".html_safe, new_csv_path(ids: @ids,format: "csv"), class: "text-center", id: "csv_download", method: 'post'%>

app/views/skus/_form.html.erb
<%= form_tag skus_path(id: params[:id]),method: "post", multipart: true do %>
  <div class="field">
    <%= label_tag :csv %><br />
    <%= file_field_tag :csv, autofocus: true %>
  </div>

  <div class="field">
    <%= label_tag :sku_denominations %>
    
    <%= text_field_tag :sku_denominations, autocomplete: "sku_denominations" %>
  </div>

  

  <div class="actions">
    <%= submit_tag "Submit" %>
  </div>
<% end %>

app/views/skus/create.js.erb
$("#sku_form").hide();
$("#new_csv_load").show();
$("#new_csv_load").html('<%= escape_javascript(render partial: "download_csv_file") %>');

app/views/skus/new.html.erb
<%= link_to "<button>SKU denomination creation</button>".html_safe, "#", class: "text-center", id: "sku_create" %>
<div class= "sku_form" id="sku_form">
	<%= form_tag skus_path(id: params[:id]),method: "post", id: "new_sku_form", remote: true, multipart: true  do %>
  <div class="field">
    <%= label_tag :csv,"Upload CSV" %><br />
    <%= file_field_tag :csv, autofocus: true %>
  </div>

  <div class="field">
    <%= label_tag :sku_denominations %>
    
    <%= text_field_tag :sku_denominations  %>
  </div>

  

  <div class="actions">
    <%= submit_tag "Submit" %>
  </div>
<% end %>

</div>
<div id="new_csv_load">
	<%= render partial: "download_csv_file"%>
</div>

<script>
	$('#new_sku_form').validate({
     rules: {
      "csv" :  { required: true },
      "sku_denominations": { required: true },
     },
     message: {
     
      "csv": {required: "*This field is mandatory"},
      "sku_denominations": { required:  "*This field is mandatory" },
    }
  });
	$("#sku_form").hide();
	$("#new_csv_load").hide();
	$("#sku_create").click(function(){
      $("#sku_form").show();
	});
	
</script>